### Server Properties
server:
  port: ${PORT:5000}
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/pokemon_data?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
#    username: root
#    password:
    ## Heroku
    url: postgres://kohgxjahedmnai:8b5a53a4a6e51e37ce6954ca106641fb75824341084df7d327d9f4cbad620d20@ec2-52-86-223-172.compute-1.amazonaws.com:5432/d40grobs4qfc5u?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: kohgxjahedmnai
    password: 8b5a53a4a6e51e37ce6954ca106641fb75824341084df7d327d9f4cbad620d20
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  # Initialize the datasource with available DDL and DML scripts
  sql:
    init:
      mode: always
  ## Jackson Properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
## Hibernate Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
## App Properties
app:
  jwtSecret: daddassawsawsd9999
  jwtExpirationInMs: 604800000

