### Server Properties
server:
  port: ${PORT:5000}
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/pokemon_data?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
#    username: root
#    password:
    ## Heroku
    url: jdbc:postgresql://ec2-34-200-139-9.compute-1.amazonaws.com:5432/dbrqci0j8anbs?user=gmsbrhtcyhjpqy&password=132a01a2bae1f00d65290f4e2326e85a377ea8eb8c868e100e6b07a80e1281f3?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: gmsbrhtcyhjpqy
    password: 132a01a2bae1f00d65290f4e2326e85a377ea8eb8c868e100e6b07a80e1281f3
    driver-class-name: org.postgresql.Driver
  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ##Heroku
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  # Initialize the datasource with available DDL and DML scripts
  sql:
    init:
      mode: always
  ## Jackson Properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
## Hibernate Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
## App Properties
app:
  jwtSecret: daddassawsawsd9999
  jwtExpirationInMs: 604800000

